/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type CommonModelsCoreSetting struct {
	Identifier string `json:"identifier,omitempty"`
	IsDefault bool `json:"isDefault,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Summary string `json:"summary,omitempty"`
	ImagePath string `json:"imagePath,omitempty"`
	ChildSettings []CommonModelsCoreSetting `json:"childSettings,omitempty"`
}
