/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type DestinyHistoricalStatsDestinyLeaderboardEntry struct {
	// Where this player ranks on the leaderboard. A value of 1 is the top rank.
	Rank int32 `json:"rank,omitempty"`
	// Identity details of the player
	Player DestinyHistoricalStatsDestinyPlayer `json:"player,omitempty"`
	// ID of the player's best character for the reported stat.
	CharacterId int64 `json:"characterId,omitempty"`
	// Value of the stat for this player
	Value DestinyHistoricalStatsDestinyHistoricalStatsValue `json:"value,omitempty"`
}
