/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyVendorInteractionType : An enumeration of the known UI interactions for Vendors.
type DestinyVendorInteractionType int32

// List of Destiny.VendorInteractionType
const (
	UNKNOWN DestinyVendorInteractionType = "0"
	QUESTCOMPLETE DestinyVendorInteractionType = "1"
	QUESTCONTINUE DestinyVendorInteractionType = "2"
	REPUTATIONPREVIEW DestinyVendorInteractionType = "3"
	RANKUPREWARD DestinyVendorInteractionType = "4"
	TOKENTURNIN DestinyVendorInteractionType = "5"
	QUESTACCEPT DestinyVendorInteractionType = "6"
	PROGRESSTAB DestinyVendorInteractionType = "7"
	END DestinyVendorInteractionType = "8"
	START DestinyVendorInteractionType = "9"
)