/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyObjectiveGrantStyle : Some Objectives provide perks, generally as part of providing some kind of interesting modifier for a Challenge or Quest. This indicates when the Perk is granted.
type DestinyDestinyObjectiveGrantStyle int32

// List of Destiny.DestinyObjectiveGrantStyle
const (
	WHENINCOMPLETE DestinyDestinyObjectiveGrantStyle = "0"
	WHENCOMPLETE DestinyDestinyObjectiveGrantStyle = "1"
	ALWAYS DestinyDestinyObjectiveGrantStyle = "2"
)