/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyDestinyRecordToastStyle int32

// List of Destiny.DestinyRecordToastStyle
const (
	NONE DestinyDestinyRecordToastStyle = "0"
	RECORD DestinyDestinyRecordToastStyle = "1"
	LORE DestinyDestinyRecordToastStyle = "2"
	BADGE DestinyDestinyRecordToastStyle = "3"
	METARECORD DestinyDestinyRecordToastStyle = "4"
	MEDALCOMPLETE DestinyDestinyRecordToastStyle = "5"
)