/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyPresentationDisplayStyle : A hint for how the presentation node should be displayed when shown in a list. How you use this is your UI is up to you.
type DestinyDestinyPresentationDisplayStyle int32

// List of Destiny.DestinyPresentationDisplayStyle
const (
	CATEGORY DestinyDestinyPresentationDisplayStyle = "0"
	BADGE DestinyDestinyPresentationDisplayStyle = "1"
	MEDALS DestinyDestinyPresentationDisplayStyle = "2"
	COLLECTIBLE DestinyDestinyPresentationDisplayStyle = "3"
	RECORD DestinyDestinyPresentationDisplayStyle = "4"
)