/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type ForumForumFlagsEnum int32

// List of Forum.ForumFlagsEnum
const (
	NONE ForumForumFlagsEnum = "0"
	BUNGIESTAFFPOST ForumForumFlagsEnum = "1"
	FORUMNINJAPOST ForumForumFlagsEnum = "2"
	FORUMMENTORPOST ForumForumFlagsEnum = "4"
	TOPICBUNGIESTAFFPOSTED ForumForumFlagsEnum = "8"
	TOPICBUNGIEVOLUNTEERPOSTED ForumForumFlagsEnum = "16"
	QUESTIONANSWEREDBYBUNGIE ForumForumFlagsEnum = "32"
	QUESTIONANSWEREDBYNINJA ForumForumFlagsEnum = "64"
	COMMUNITYCONTENT ForumForumFlagsEnum = "128"
)