/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// An overly complicated wrapper for the item level at which the item should spawn.
type DestinyDefinitionsDestinyItemCreationEntryLevelDefinition struct {
	Level int32 `json:"level,omitempty"`
}
