/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyVendorItemState : The possible states of Destiny Profile Records. IMPORTANT: Any given item can theoretically have many of these states simultaneously: as a result, this was altered to be a flags enumeration for v3.2.0.
type DestinyDestinyVendorItemState int32

// List of Destiny.DestinyVendorItemState
const (
	NONE DestinyDestinyVendorItemState = "0"
	INCOMPLETE DestinyDestinyVendorItemState = "1"
	REWARDAVAILABLE DestinyDestinyVendorItemState = "2"
	COMPLETE DestinyDestinyVendorItemState = "4"
	NEW DestinyDestinyVendorItemState = "8"
	FEATURED DestinyDestinyVendorItemState = "16"
	ENDING DestinyDestinyVendorItemState = "32"
	ONSALE DestinyDestinyVendorItemState = "64"
	OWNED DestinyDestinyVendorItemState = "128"
	WIDEVIEW DestinyDestinyVendorItemState = "256"
	NEXUSATTENTION DestinyDestinyVendorItemState = "512"
)