/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyEquipFailureReason : The reasons why an item cannot be equipped, if any. Many flags can be set, or \"None\" if
type DestinyEquipFailureReason int32

// List of Destiny.EquipFailureReason
const (
	NONE DestinyEquipFailureReason = "0"
	ITEMUNEQUIPPABLE DestinyEquipFailureReason = "1"
	ITEMUNIQUEEQUIPRESTRICTED DestinyEquipFailureReason = "2"
	ITEMFAILEDUNLOCKCHECK DestinyEquipFailureReason = "4"
	ITEMFAILEDLEVELCHECK DestinyEquipFailureReason = "8"
	ITEMNOTONCHARACTER DestinyEquipFailureReason = "16"
)