/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type DestinyDefinitionsRecordsDestinyRecordDefinition struct {
	DisplayProperties DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition `json:"displayProperties,omitempty"`
	// Indicates whether this Record's state is determined on a per-character or on an account-wide basis.
	Scope DestinyDestinyScope `json:"scope,omitempty"`
	PresentationInfo DestinyDefinitionsPresentationDestinyPresentationChildBlock `json:"presentationInfo,omitempty"`
	LoreHash int32 `json:"loreHash,omitempty"`
	ObjectiveHashes []int32 `json:"objectiveHashes,omitempty"`
	RecordValueStyle DestinyDestinyRecordValueStyle `json:"recordValueStyle,omitempty"`
	TitleInfo DestinyDefinitionsRecordsDestinyRecordTitleBlock `json:"titleInfo,omitempty"`
	CompletionInfo DestinyDefinitionsRecordsDestinyRecordCompletionBlock `json:"completionInfo,omitempty"`
	StateInfo DestinyDefinitionsRecordsSchemaRecordStateBlock `json:"stateInfo,omitempty"`
	Requirements DestinyDefinitionsPresentationDestinyPresentationNodeRequirementsBlock `json:"requirements,omitempty"`
	// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
	Hash int32 `json:"hash,omitempty"`
	// The index of the entity as it was found in the investment tables.
	Index int32 `json:"index,omitempty"`
	// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
	Redacted bool `json:"redacted,omitempty"`
}
