/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type CommonModelsCoreSettingsConfiguration struct {
	Systems map[string]CommonModelsCoreSystem `json:"systems,omitempty"`
	IgnoreReasons []CommonModelsCoreSetting `json:"ignoreReasons,omitempty"`
	ForumCategories []CommonModelsCoreSetting `json:"forumCategories,omitempty"`
	GroupAvatars []CommonModelsCoreSetting `json:"groupAvatars,omitempty"`
	DestinyMembershipTypes []CommonModelsCoreSetting `json:"destinyMembershipTypes,omitempty"`
	RecruitmentPlatformTags []CommonModelsCoreSetting `json:"recruitmentPlatformTags,omitempty"`
	RecruitmentMiscTags []CommonModelsCoreSetting `json:"recruitmentMiscTags,omitempty"`
	RecruitmentActivities []CommonModelsCoreSetting `json:"recruitmentActivities,omitempty"`
	UserContentLocales []CommonModelsCoreSetting `json:"userContentLocales,omitempty"`
	SystemContentLocales []CommonModelsCoreSetting `json:"systemContentLocales,omitempty"`
	ClanBannerDecals []CommonModelsCoreSetting `json:"clanBannerDecals,omitempty"`
	ClanBannerDecalColors []CommonModelsCoreSetting `json:"clanBannerDecalColors,omitempty"`
	ClanBannerGonfalons []CommonModelsCoreSetting `json:"clanBannerGonfalons,omitempty"`
	ClanBannerGonfalonColors []CommonModelsCoreSetting `json:"clanBannerGonfalonColors,omitempty"`
	ClanBannerGonfalonDetails []CommonModelsCoreSetting `json:"clanBannerGonfalonDetails,omitempty"`
	ClanBannerGonfalonDetailColors []CommonModelsCoreSetting `json:"clanBannerGonfalonDetailColors,omitempty"`
	ClanBannerStandards []CommonModelsCoreSetting `json:"clanBannerStandards,omitempty"`
	Destiny2CoreSettings CommonModelsDestiny2CoreSettings `json:"destiny2CoreSettings,omitempty"`
}
