/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type FireteamFireteamActivityType int32

// List of Fireteam.FireteamActivityType
const (
	ALL FireteamFireteamActivityType = "0"
	RAID FireteamFireteamActivityType = "1"
	CRUCIBLE FireteamFireteamActivityType = "2"
	TRIALS FireteamFireteamActivityType = "3"
	NIGHTFALL FireteamFireteamActivityType = "4"
	ANYTHING FireteamFireteamActivityType = "5"
	GAMBIT FireteamFireteamActivityType = "6"
	BLINDWELL FireteamFireteamActivityType = "7"
	ESCALATIONPROTOCOL FireteamFireteamActivityType = "8"
)