/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
import (
	"time"
)

type DestinyResponsesDestinyProfileUserInfoCard struct {
	DateLastPlayed time.Time `json:"dateLastPlayed,omitempty"`
	// A platform specific additional display name - ex: psn Real Name, bnet Unique Name, etc.
	SupplementalDisplayName string `json:"supplementalDisplayName,omitempty"`
	// URL the Icon if available.
	IconPath string `json:"iconPath,omitempty"`
	// Type of the membership.
	MembershipType BungieMembershipType `json:"membershipType,omitempty"`
	// Membership ID as they user is known in the Accounts service
	MembershipId int64 `json:"membershipId,omitempty"`
	// Display Name the player has chosen for themselves. The display name is optional when the data type is used as input to a platform API.
	DisplayName string `json:"displayName,omitempty"`
}
