/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyDestinyAmmunitionType int32

// List of Destiny.DestinyAmmunitionType
const (
	NONE DestinyDestinyAmmunitionType = "0"
	PRIMARY DestinyDestinyAmmunitionType = "1"
	SPECIAL DestinyDestinyAmmunitionType = "2"
	HEAVY DestinyDestinyAmmunitionType = "3"
	UNKNOWN DestinyDestinyAmmunitionType = "4"
)