/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyItemSubType : This Enumeration further classifies items by more specific categorizations than DestinyItemType. The \"Sub-Type\" is where we classify and categorize items one step further in specificity: \"Auto Rifle\" instead of just \"Weapon\" for example, or \"Vanguard Bounty\" instead of merely \"Bounty\".  These sub-types are provided for historical compatibility with Destiny 1, but an ideal alternative is to use DestinyItemCategoryDefinitions and the DestinyItemDefinition.itemCategories property instead. Item Categories allow for arbitrary hierarchies of specificity, and for items to belong to multiple categories across multiple hierarchies simultaneously. For this enum, we pick a single type as a \"best guess\" fit.  NOTE: This is not all of the item types available, and some of these are holdovers from Destiny 1 that may or may not still exist.
type DestinyDestinyItemSubType int32

// List of Destiny.DestinyItemSubType
const (
	NONE DestinyDestinyItemSubType = "0"
	CRUCIBLE DestinyDestinyItemSubType = "1"
	VANGUARD DestinyDestinyItemSubType = "2"
	EXOTIC DestinyDestinyItemSubType = "5"
	AUTORIFLE DestinyDestinyItemSubType = "6"
	SHOTGUN DestinyDestinyItemSubType = "7"
	MACHINEGUN DestinyDestinyItemSubType = "8"
	HANDCANNON DestinyDestinyItemSubType = "9"
	ROCKETLAUNCHER DestinyDestinyItemSubType = "10"
	FUSIONRIFLE DestinyDestinyItemSubType = "11"
	SNIPERRIFLE DestinyDestinyItemSubType = "12"
	PULSERIFLE DestinyDestinyItemSubType = "13"
	SCOUTRIFLE DestinyDestinyItemSubType = "14"
	CRM DestinyDestinyItemSubType = "16"
	SIDEARM DestinyDestinyItemSubType = "17"
	SWORD DestinyDestinyItemSubType = "18"
	MASK DestinyDestinyItemSubType = "19"
	SHADER DestinyDestinyItemSubType = "20"
	ORNAMENT DestinyDestinyItemSubType = "21"
	FUSIONRIFLELINE DestinyDestinyItemSubType = "22"
	GRENADELAUNCHER DestinyDestinyItemSubType = "23"
	SUBMACHINEGUN DestinyDestinyItemSubType = "24"
	TRACERIFLE DestinyDestinyItemSubType = "25"
	HELMETARMOR DestinyDestinyItemSubType = "26"
	GAUNTLETSARMOR DestinyDestinyItemSubType = "27"
	CHESTARMOR DestinyDestinyItemSubType = "28"
	LEGARMOR DestinyDestinyItemSubType = "29"
	CLASSARMOR DestinyDestinyItemSubType = "30"
	BOW DestinyDestinyItemSubType = "31"
)