/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type ApplicationsApiUsage struct {
	// The date range for the data being reported.
	Range DatesDateRange `json:"range,omitempty"`
	// Counts for on API calls made for the time range.
	ApiCalls []ApplicationsSeries `json:"apiCalls,omitempty"`
	// Instances of blocked requests or requests that crossed the warn threshold during the time range.
	ThrottledRequests []ApplicationsSeries `json:"throttledRequests,omitempty"`
}
