/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyActivityDifficultyTier : An enumeration representing the potential difficulty levels of an activity. Their names are... more qualitative than quantitative.
type DestinyDestinyActivityDifficultyTier int32

// List of Destiny.DestinyActivityDifficultyTier
const (
	TRIVIAL DestinyDestinyActivityDifficultyTier = "0"
	EASY DestinyDestinyActivityDifficultyTier = "1"
	NORMAL DestinyDestinyActivityDifficultyTier = "2"
	CHALLENGING DestinyDestinyActivityDifficultyTier = "3"
	HARD DestinyDestinyActivityDifficultyTier = "4"
	BRAVE DestinyDestinyActivityDifficultyTier = "5"
	ALMOSTIMPOSSIBLE DestinyDestinyActivityDifficultyTier = "6"
	IMPOSSIBLE DestinyDestinyActivityDifficultyTier = "7"
)