/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyProgressionStepDisplayEffect : If progression is earned, this determines whether the progression shows visual effects on the character or its item - or neither.
type DestinyDestinyProgressionStepDisplayEffect int32

// List of Destiny.DestinyProgressionStepDisplayEffect
const (
	NONE DestinyDestinyProgressionStepDisplayEffect = "0"
	CHARACTER DestinyDestinyProgressionStepDisplayEffect = "1"
	ITEM DestinyDestinyProgressionStepDisplayEffect = "2"
)