/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// ComponentsComponentPrivacySetting : A set of flags for reason(s) why the component populated in the way that it did. Inspect the individual flags for the reasons.
type ComponentsComponentPrivacySetting int32

// List of Components.ComponentPrivacySetting
const (
	NONE ComponentsComponentPrivacySetting = "0"
	PUBLIC ComponentsComponentPrivacySetting = "1"
	PRIVATE ComponentsComponentPrivacySetting = "2"
)