/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// These definitions represent vendors' locations and relevant display information at different times in the game.
type DestinyDefinitionsVendorsDestinyVendorLocationDefinition struct {
	// The hash identifier for a Destination at which this vendor may be located. Each destination where a Vendor may exist will only ever have a single entry.
	DestinationHash int32 `json:"destinationHash,omitempty"`
	// The relative path to the background image representing this Vendor at this location, for use in a banner.
	BackgroundImagePath string `json:"backgroundImagePath,omitempty"`
}
