/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyVendorInteractionRewardSelection : When a Vendor Interaction provides rewards, they'll either let you choose one or let you have all of them. This determines which it will be.
type DestinyDestinyVendorInteractionRewardSelection int32

// List of Destiny.DestinyVendorInteractionRewardSelection
const (
	NONE DestinyDestinyVendorInteractionRewardSelection = "0"
	ONE DestinyDestinyVendorInteractionRewardSelection = "1"
	ALL DestinyDestinyVendorInteractionRewardSelection = "2"
)