/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// A response containing all of the components for a vendor.
type DestinyResponsesDestinyVendorResponse struct {
	// The base properties of the vendor.  COMPONENT TYPE: Vendors
	Vendor SingleComponentResponseOfDestinyVendorComponent `json:"vendor,omitempty"`
	// Categories that the vendor has available, and references to the sales therein.  COMPONENT TYPE: VendorCategories
	Categories SingleComponentResponseOfDestinyVendorCategoriesComponent `json:"categories,omitempty"`
	// Sales, keyed by the vendorItemIndex of the item being sold.  COMPONENT TYPE: VendorSales
	Sales DictionaryComponentResponseOfint32AndDestinyVendorSaleItemComponent `json:"sales,omitempty"`
	// Item components, keyed by the vendorItemIndex of the active sale items.  COMPONENT TYPE: [See inside the DestinyItemComponentSet contract for component types.]
	ItemComponents DestinyItemComponentSetOfint32 `json:"itemComponents,omitempty"`
	// A \"lookup\" convenience component that can be used to quickly check if the character has access to items that can be used for purchasing.  COMPONENT TYPE: CurrencyLookups
	CurrencyLookups SingleComponentResponseOfDestinyCurrenciesComponent `json:"currencyLookups,omitempty"`
}
