/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// As/if presentation nodes begin to host more entities as children, these lists will be added to. One list property exists per type of entity that can be treated as a child of this presentation node, and each holds the identifier of the entity and any associated information needed to display the UI for that entity (if anything)
type DestinyDefinitionsPresentationDestinyPresentationNodeChildrenBlock struct {
	PresentationNodes []DestinyDefinitionsPresentationDestinyPresentationNodeChildEntry `json:"presentationNodes,omitempty"`
	Collectibles []DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry `json:"collectibles,omitempty"`
	Records []DestinyDefinitionsPresentationDestinyPresentationNodeRecordChildEntry `json:"records,omitempty"`
}
