/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDefinitionsMilestonesDestinyMilestoneType : The type of milestone. Milestones can be Tutorials, one-time/triggered/non-repeating but not necessarily tutorials, or Repeating Milestones.
type DestinyDefinitionsMilestonesDestinyMilestoneType int32

// List of Destiny.Definitions.Milestones.DestinyMilestoneType
const (
	UNKNOWN DestinyDefinitionsMilestonesDestinyMilestoneType = "0"
	TUTORIAL DestinyDefinitionsMilestonesDestinyMilestoneType = "1"
	ONETIME DestinyDefinitionsMilestonesDestinyMilestoneType = "2"
	WEEKLY DestinyDefinitionsMilestonesDestinyMilestoneType = "3"
	DAILY DestinyDefinitionsMilestonesDestinyMilestoneType = "4"
	SPECIAL DestinyDefinitionsMilestonesDestinyMilestoneType = "5"
)