/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type GroupsV2GroupPotentialMemberStatus int32

// List of GroupsV2.GroupPotentialMemberStatus
const (
	NONE GroupsV2GroupPotentialMemberStatus = "0"
	APPLICANT GroupsV2GroupPotentialMemberStatus = "1"
	INVITEE GroupsV2GroupPotentialMemberStatus = "2"
)