/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes int32

// List of Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes
const (
	NONE DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "0"
	STATS DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "1"
	SHIELDS DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "2"
	HEALTH DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "4"
	REVIVE DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "8"
	AIMUNDERFIRE DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "16"
	RADAR DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "32"
	INVISIBILITY DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "64"
	REPUTATIONS DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "128"
	ALL DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes = "255"
)