/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
import (
	"time"
)

type FireteamFireteamSummary struct {
	FireteamId int64 `json:"fireteamId,omitempty"`
	GroupId int64 `json:"groupId,omitempty"`
	Platform FireteamFireteamPlatform `json:"platform,omitempty"`
	ActivityType FireteamFireteamActivityType `json:"activityType,omitempty"`
	IsImmediate bool `json:"isImmediate,omitempty"`
	ScheduledTime time.Time `json:"scheduledTime,omitempty"`
	OwnerMembershipId int64 `json:"ownerMembershipId,omitempty"`
	PlayerSlotCount int32 `json:"playerSlotCount,omitempty"`
	AlternateSlotCount int32 `json:"alternateSlotCount,omitempty"`
	AvailablePlayerSlotCount int32 `json:"availablePlayerSlotCount,omitempty"`
	AvailableAlternateSlotCount int32 `json:"availableAlternateSlotCount,omitempty"`
	Title string `json:"title,omitempty"`
	DateCreated time.Time `json:"dateCreated,omitempty"`
	DateModified time.Time `json:"dateModified,omitempty"`
	IsPublic bool `json:"isPublic,omitempty"`
	Locale string `json:"locale,omitempty"`
	IsValid bool `json:"isValid,omitempty"`
	DatePlayerModified time.Time `json:"datePlayerModified,omitempty"`
}
