/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// When a Graph needs to show active Progressions, this defines those objectives as well as an identifier.
type DestinyDefinitionsDirectorDestinyActivityGraphDisplayProgressionDefinition struct {
	Id int32 `json:"id,omitempty"`
	ProgressionHash int32 `json:"progressionHash,omitempty"`
}
