/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// Guided Game information for this activity.
type DestinyDefinitionsDestinyActivityGuidedBlockDefinition struct {
	// The maximum amount of people that can be in the waiting lobby.
	GuidedMaxLobbySize int32 `json:"guidedMaxLobbySize,omitempty"`
	// The minimum amount of people that can be in the waiting lobby.
	GuidedMinLobbySize int32 `json:"guidedMinLobbySize,omitempty"`
	// If -1, the guided group cannot be disbanded. Otherwise, take the total # of players in the activity and subtract this number: that is the total # of votes needed for the guided group to disband.
	GuidedDisbandCount int32 `json:"guidedDisbandCount,omitempty"`
}
