/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyHistoricalStatsDefinitionsUnitType int32

// List of Destiny.HistoricalStats.Definitions.UnitType
const (
	NONE DestinyHistoricalStatsDefinitionsUnitType = "0"
	COUNT DestinyHistoricalStatsDefinitionsUnitType = "1"
	PERGAME DestinyHistoricalStatsDefinitionsUnitType = "2"
	SECONDS DestinyHistoricalStatsDefinitionsUnitType = "3"
	POINTS DestinyHistoricalStatsDefinitionsUnitType = "4"
	TEAM DestinyHistoricalStatsDefinitionsUnitType = "5"
	DISTANCE DestinyHistoricalStatsDefinitionsUnitType = "6"
	PERCENT DestinyHistoricalStatsDefinitionsUnitType = "7"
	RATIO DestinyHistoricalStatsDefinitionsUnitType = "8"
	BOOLEAN DestinyHistoricalStatsDefinitionsUnitType = "9"
	WEAPONTYPE DestinyHistoricalStatsDefinitionsUnitType = "10"
	STANDING DestinyHistoricalStatsDefinitionsUnitType = "11"
	MILLISECONDS DestinyHistoricalStatsDefinitionsUnitType = "12"
	COMPLETIONREASON DestinyHistoricalStatsDefinitionsUnitType = "13"
)