/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// When the interaction is replied to, Reward sites will fire and items potentially selected based on whether the given unlock expression is TRUE.  You can potentially choose one from multiple replies when replying to an interaction: this is how you get either/or rewards from vendors.
type DestinyDefinitionsDestinyVendorInteractionReplyDefinition struct {
	// The rewards granted upon responding to the vendor.
	ItemRewardsSelection DestinyDestinyVendorInteractionRewardSelection `json:"itemRewardsSelection,omitempty"`
	// The localized text for the reply.
	Reply string `json:"reply,omitempty"`
	// An enum indicating the type of reply being made.
	ReplyType DestinyDestinyVendorReplyType `json:"replyType,omitempty"`
}
