/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type DestinyItemComponentSetOfint32 struct {
	Instances DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent `json:"instances,omitempty"`
	Perks DictionaryComponentResponseOfint32AndDestinyItemPerksComponent `json:"perks,omitempty"`
	RenderData DictionaryComponentResponseOfint32AndDestinyItemRenderComponent `json:"renderData,omitempty"`
	Stats DictionaryComponentResponseOfint32AndDestinyItemStatsComponent `json:"stats,omitempty"`
	Sockets DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent `json:"sockets,omitempty"`
	TalentGrids DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent `json:"talentGrids,omitempty"`
	PlugStates DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent `json:"plugStates,omitempty"`
	Objectives DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent `json:"objectives,omitempty"`
}
