/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// A reference to an Activity Modifier from another entity, such as an Activity (for now, just Activities).  This defines some
type DestinyDefinitionsDestinyActivityModifierReferenceDefinition struct {
	// The hash identifier for the DestinyActivityModifierDefinition referenced by this activity.
	ActivityModifierHash int32 `json:"activityModifierHash,omitempty"`
}
