/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type ApplicationsApplicationStatus int32

// List of Applications.ApplicationStatus
const (
	NONE ApplicationsApplicationStatus = "0"
	PRIVATE ApplicationsApplicationStatus = "1"
	PUBLIC ApplicationsApplicationStatus = "2"
	DISABLED ApplicationsApplicationStatus = "3"
	BLOCKED ApplicationsApplicationStatus = "4"
)