/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type FireteamFireteamDateRange int32

// List of Fireteam.FireteamDateRange
const (
	ALL FireteamFireteamDateRange = "0"
	NOW FireteamFireteamDateRange = "1"
	TWENTYFOURHOURS FireteamFireteamDateRange = "2"
	FORTYEIGHTHOURS FireteamFireteamDateRange = "3"
	THISWEEK FireteamFireteamDateRange = "4"
)