/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyItemState : A flags enumeration where each bit represents a different possible state that the item can be in that may effect how the item is displayed to the user and what actions can be performed against it.
type DestinyItemState int32

// List of Destiny.ItemState
const (
	NONE DestinyItemState = "0"
	LOCKED DestinyItemState = "1"
	TRACKED DestinyItemState = "2"
	MASTERWORK DestinyItemState = "4"
)