/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type CommonModelsDestiny2CoreSettings struct {
	CollectionRootNode int32 `json:"collectionRootNode,omitempty"`
	BadgesRootNode int32 `json:"badgesRootNode,omitempty"`
	RecordsRootNode int32 `json:"recordsRootNode,omitempty"`
	MedalsRootNode int32 `json:"medalsRootNode,omitempty"`
	UndiscoveredCollectibleImage string `json:"undiscoveredCollectibleImage,omitempty"`
	AmmoTypeHeavyIcon string `json:"ammoTypeHeavyIcon,omitempty"`
	AmmoTypeSpecialIcon string `json:"ammoTypeSpecialIcon,omitempty"`
	AmmoTypePrimaryIcon string `json:"ammoTypePrimaryIcon,omitempty"`
}
