/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// This contract contains clan-specific group information. It does not include any investment data.
type GroupsV2GroupV2ClanInfo struct {
	ClanCallsign string `json:"clanCallsign,omitempty"`
	ClanBannerData GroupsV2ClanBanner `json:"clanBannerData,omitempty"`
}
