/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// Presentation nodes can be restricted by various requirements. This defines the rules of those requirements, and the message(s) to be shown if these requirements aren't met.
type DestinyDefinitionsPresentationDestinyPresentationNodeRequirementsBlock struct {
	// If this node is not accessible due to Entitlements (for instance, you don't own the required game expansion), this is the message to show.
	EntitlementUnavailableMessage string `json:"entitlementUnavailableMessage,omitempty"`
}
