/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
import (
	"time"
)

type GroupsV2GroupBan struct {
	GroupId int64 `json:"groupId,omitempty"`
	LastModifiedBy UserUserInfoCard `json:"lastModifiedBy,omitempty"`
	CreatedBy UserUserInfoCard `json:"createdBy,omitempty"`
	DateBanned time.Time `json:"dateBanned,omitempty"`
	DateExpires time.Time `json:"dateExpires,omitempty"`
	Comment string `json:"comment,omitempty"`
	BungieNetUserInfo UserUserInfoCard `json:"bungieNetUserInfo,omitempty"`
	DestinyUserInfo UserUserInfoCard `json:"destinyUserInfo,omitempty"`
}
