/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type GroupsV2ClanBanner struct {
	DecalId int32 `json:"decalId,omitempty"`
	DecalColorId int32 `json:"decalColorId,omitempty"`
	DecalBackgroundColorId int32 `json:"decalBackgroundColorId,omitempty"`
	GonfalonId int32 `json:"gonfalonId,omitempty"`
	GonfalonColorId int32 `json:"gonfalonColorId,omitempty"`
	GonfalonDetailId int32 `json:"gonfalonDetailId,omitempty"`
	GonfalonDetailColorId int32 `json:"gonfalonDetailColorId,omitempty"`
}
