/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type DestinyHistoricalStatsDestinyPostGameCarnageReportTeamEntry struct {
	// Integer ID for the team.
	TeamId int32 `json:"teamId,omitempty"`
	// Team's standing relative to other teams.
	Standing DestinyHistoricalStatsDestinyHistoricalStatsValue `json:"standing,omitempty"`
	// Score earned by the team
	Score DestinyHistoricalStatsDestinyHistoricalStatsValue `json:"score,omitempty"`
	// Alpha or Bravo
	TeamName string `json:"teamName,omitempty"`
}
