/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyItemSortType : Determines how items are sorted in an inventory bucket.
type DestinyDestinyItemSortType int32

// List of Destiny.DestinyItemSortType
const (
	ITEMID DestinyDestinyItemSortType = "0"
	TIMESTAMP DestinyDestinyItemSortType = "1"
	STACKSIZE DestinyDestinyItemSortType = "2"
)