/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// The base class for any component-returning object that may need to indicate information about the state of the component being returned.
type ComponentsComponentResponse struct {
	Privacy ComponentsComponentPrivacySetting `json:"privacy,omitempty"`
}
