/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyStatAggregationType : When a Stat (DestinyStatDefinition) is aggregated, this is the rules used for determining the level and formula used for aggregation.  * CharacterAverage = apply a weighted average using the related DestinyStatGroupDefinition on the DestinyInventoryItemDefinition across the character's equipped items. See both of those definitions for details. * Character = don't aggregate: the stat should be located and used directly on the character. * Item = don't aggregate: the stat should be located and used directly on the item.
type DestinyDestinyStatAggregationType int32

// List of Destiny.DestinyStatAggregationType
const (
	CHARACTERAVERAGE DestinyDestinyStatAggregationType = "0"
	CHARACTER DestinyDestinyStatAggregationType = "1"
	ITEM DestinyDestinyStatAggregationType = "2"
)