/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// GroupsV2RuntimeGroupMemberType : The member levels used by all V2 Groups API. Individual group types use their own mappings in their native storage (general uses BnetDbGroupMemberType and D2 clans use ClanMemberLevel), but they are all translated to this in the runtime api. These runtime values should NEVER be stored anywhere, so the values can be changed as necessary.
type GroupsV2RuntimeGroupMemberType int32

// List of GroupsV2.RuntimeGroupMemberType
const (
	NONE GroupsV2RuntimeGroupMemberType = "0"
	BEGINNER GroupsV2RuntimeGroupMemberType = "1"
	MEMBER GroupsV2RuntimeGroupMemberType = "2"
	ADMIN GroupsV2RuntimeGroupMemberType = "3"
	ACTINGFOUNDER GroupsV2RuntimeGroupMemberType = "4"
	FOUNDER GroupsV2RuntimeGroupMemberType = "5"
)