/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances int32

// List of Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances
const (
	NONE DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "0"
	RATEOFFIRE DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "1"
	DAMAGE DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "2"
	ACCURACY DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "4"
	RANGE DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "8"
	ZOOM DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "16"
	RECOIL DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "32"
	READY DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "64"
	RELOAD DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "128"
	HAIRTRIGGER DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "256"
	AMMOANDMAGAZINE DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "512"
	TRACKINGANDDETONATION DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "1024"
	SHOTGUNSPREAD DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "2048"
	CHARGETIME DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "4096"
	ALL DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances = "8191"
)