/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type ForumForumTopicsSortEnum int32

// List of Forum.ForumTopicsSortEnum
const (
	DEFAULT ForumForumTopicsSortEnum = "0"
	LASTREPLIED ForumForumTopicsSortEnum = "1"
	MOSTREPLIED ForumForumTopicsSortEnum = "2"
	POPULARITY ForumForumTopicsSortEnum = "3"
	CONTROVERSIALITY ForumForumTopicsSortEnum = "4"
	LIKED ForumForumTopicsSortEnum = "5"
	HIGHESTRATED ForumForumTopicsSortEnum = "6"
	MOSTUPVOTED ForumForumTopicsSortEnum = "7"
)