/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinySpecialItemType : As you run into items that need to be classified for Milestone purposes in ways that we cannot infer via direct data, add a new classification here and use a string constant to represent it in the local item config file.  NOTE: This is not all of the item types available, and some of these are holdovers from Destiny 1 that may or may not still exist.
type DestinySpecialItemType int32

// List of Destiny.SpecialItemType
const (
	NONE DestinySpecialItemType = "0"
	SPECIALCURRENCY DestinySpecialItemType = "1"
	ARMOR DestinySpecialItemType = "8"
	WEAPON DestinySpecialItemType = "9"
	ENGRAM DestinySpecialItemType = "23"
	CONSUMABLE DestinySpecialItemType = "24"
	EXCHANGEMATERIAL DestinySpecialItemType = "25"
	MISSIONREWARD DestinySpecialItemType = "27"
	CURRENCY DestinySpecialItemType = "29"
)