/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyDefinitionsDestinyTalentNodeStepImpactEffects int32

// List of Destiny.Definitions.DestinyTalentNodeStepImpactEffects
const (
	NONE DestinyDefinitionsDestinyTalentNodeStepImpactEffects = "0"
	ARMORPIERCING DestinyDefinitionsDestinyTalentNodeStepImpactEffects = "1"
	RICOCHET DestinyDefinitionsDestinyTalentNodeStepImpactEffects = "2"
	FLINCH DestinyDefinitionsDestinyTalentNodeStepImpactEffects = "4"
	COLLATERALDAMAGE DestinyDefinitionsDestinyTalentNodeStepImpactEffects = "8"
	DISORIENT DestinyDefinitionsDestinyTalentNodeStepImpactEffects = "16"
	HIGHLIGHTTARGET DestinyDefinitionsDestinyTalentNodeStepImpactEffects = "32"
	ALL DestinyDefinitionsDestinyTalentNodeStepImpactEffects = "63"
)