/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyTransferStatuses : Whether you can transfer an item, and why not if you can't.
type DestinyTransferStatuses int32

// List of Destiny.TransferStatuses
const (
	CANTRANSFER DestinyTransferStatuses = "0"
	ITEMISEQUIPPED DestinyTransferStatuses = "1"
	NOTTRANSFERRABLE DestinyTransferStatuses = "2"
	NOROOMINDESTINATION DestinyTransferStatuses = "4"
)