/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// These properties are an attempt to categorize talent node steps by certain common properties. See the related enumerations for the type of properties being categorized.
type DestinyDefinitionsDestinyTalentNodeStepGroups struct {
	WeaponPerformance DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances `json:"weaponPerformance,omitempty"`
	ImpactEffects DestinyDefinitionsDestinyTalentNodeStepImpactEffects `json:"impactEffects,omitempty"`
	GuardianAttributes DestinyDefinitionsDestinyTalentNodeStepGuardianAttributes `json:"guardianAttributes,omitempty"`
	LightAbilities DestinyDefinitionsDestinyTalentNodeStepLightAbilities `json:"lightAbilities,omitempty"`
	DamageTypes DestinyDefinitionsDestinyTalentNodeStepDamageTypes `json:"damageTypes,omitempty"`
}
