/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type GroupsV2GroupsForMemberFilter int32

// List of GroupsV2.GroupsForMemberFilter
const (
	ALL GroupsV2GroupsForMemberFilter = "0"
	FOUNDED GroupsV2GroupsForMemberFilter = "1"
	NONFOUNDED GroupsV2GroupsForMemberFilter = "2"
)