/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType int32

// List of Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType
const (
	NONE DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "0"
	KILLS DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "1"
	ASSISTS DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "2"
	DEATHS DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "3"
	CRITICALS DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "4"
	KDA DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "5"
	KD DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "6"
	SCORE DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "7"
	ENTERED DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "8"
	TIMEPLAYED DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "9"
	MEDALWINS DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "10"
	MEDALGAME DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "11"
	MEDALSPECIALKILLS DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "12"
	MEDALSPREES DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "13"
	MEDALMULTIKILLS DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "14"
	MEDALABILITIES DestinyHistoricalStatsDefinitionsDestinyStatsCategoryType = "15"
)