/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyItemPerkVisibility : Indicates how a perk should be shown, or if it should be, in the game UI. Maybe useful for those of you trying to filter out internal-use-only perks (or for those of you trying to figure out what they do!)
type DestinyItemPerkVisibility int32

// List of Destiny.ItemPerkVisibility
const (
	VISIBLE DestinyItemPerkVisibility = "0"
	DISABLED DestinyItemPerkVisibility = "1"
	HIDDEN DestinyItemPerkVisibility = "2"
)