/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// TrendingTrendingEntryType : The known entity types that you can have returned from Trending.
type TrendingTrendingEntryType int32

// List of Trending.TrendingEntryType
const (
	NEWS TrendingTrendingEntryType = "0"
	DESTINYITEM TrendingTrendingEntryType = "1"
	DESTINYACTIVITY TrendingTrendingEntryType = "2"
	DESTINYRITUAL TrendingTrendingEntryType = "3"
	SUPPORTARTICLE TrendingTrendingEntryType = "4"
	CREATION TrendingTrendingEntryType = "5"
	STREAM TrendingTrendingEntryType = "6"
	UPDATE TrendingTrendingEntryType = "7"
	LINK TrendingTrendingEntryType = "8"
	FORUMTAG TrendingTrendingEntryType = "9"
	CONTAINER TrendingTrendingEntryType = "10"
	RELEASE TrendingTrendingEntryType = "11"
)