/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyPlugUiStyles : If the plug has a specific custom style, this enumeration will represent that style/those styles.
type DestinyPlugUiStyles int32

// List of Destiny.PlugUiStyles
const (
	NONE DestinyPlugUiStyles = "0"
	MASTERWORK DestinyPlugUiStyles = "1"
)