/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type ApplicationsApplicationScopes int64

// List of Applications.ApplicationScopes
const (
	READBASICUSERPROFILE ApplicationsApplicationScopes = "1"
	READGROUPS ApplicationsApplicationScopes = "2"
	WRITEGROUPS ApplicationsApplicationScopes = "4"
	ADMINGROUPS ApplicationsApplicationScopes = "8"
	BNETWRITE ApplicationsApplicationScopes = "16"
	MOVEEQUIPDESTINYITEMS ApplicationsApplicationScopes = "32"
	READDESTINYINVENTORYANDVAULT ApplicationsApplicationScopes = "64"
	READUSERDATA ApplicationsApplicationScopes = "128"
	EDITUSERDATA ApplicationsApplicationScopes = "256"
	READDESTINYVENDORSANDADVISORS ApplicationsApplicationScopes = "512"
	READANDAPPLYTOKENS ApplicationsApplicationScopes = "1024"
	ADVANCEDWRITEACTIONS ApplicationsApplicationScopes = "2048"
)