/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinySocketTypeActionType : Indicates the type of actions that can be performed
type DestinySocketTypeActionType int32

// List of Destiny.SocketTypeActionType
const (
	INSERTPLUG DestinySocketTypeActionType = "0"
	INFUSEITEM DestinySocketTypeActionType = "1"
	REINITIALIZESOCKET DestinySocketTypeActionType = "2"
)