/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyActivityGraphNodeHighlightType : The various known UI styles in which an item can be highlighted. It'll be up to you to determine what you want to show based on this highlighting, BNet doesn't have any assets that correspond to these states. And yeah, RiseOfIron and Comet have their own special highlight states. Don't ask me, I can't imagine they're still used.
type DestinyActivityGraphNodeHighlightType int32

// List of Destiny.ActivityGraphNodeHighlightType
const (
	NONE DestinyActivityGraphNodeHighlightType = "0"
	NORMAL DestinyActivityGraphNodeHighlightType = "1"
	HYPER DestinyActivityGraphNodeHighlightType = "2"
	COMET DestinyActivityGraphNodeHighlightType = "3"
	RISEOFIRON DestinyActivityGraphNodeHighlightType = "4"
)