/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type DestinyComponentsPresentationDestinyPresentationNodeComponent struct {
	State DestinyDestinyPresentationNodeState `json:"state,omitempty"`
	// An optional property: presentation nodes MAY have objectives, which can be used to infer more human readable data about the progress. However, progressValue and completionValue ought to be considered the canonical values for progress on Progression Nodes.
	Objective DestinyQuestsDestinyObjectiveProgress `json:"objective,omitempty"`
	// How much of the presentation node is considered to be completed so far by the given character/profile.
	ProgressValue int32 `json:"progressValue,omitempty"`
	// The value at which the presentation ode is considered to be completed.
	CompletionValue int32 `json:"completionValue,omitempty"`
}
