/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type FireteamFireteamPublicSearchOption int32

// List of Fireteam.FireteamPublicSearchOption
const (
	PUBLICANDPRIVATE FireteamFireteamPublicSearchOption = "0"
	PUBLICONLY FireteamFireteamPublicSearchOption = "1"
	PRIVATEONLY FireteamFireteamPublicSearchOption = "2"
)