/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyDestinySocketVisibility int32

// List of Destiny.DestinySocketVisibility
const (
	VISIBLE DestinyDestinySocketVisibility = "0"
	HIDDEN DestinyDestinySocketVisibility = "1"
	HIDDENWHENEMPTY DestinyDestinySocketVisibility = "2"
	HIDDENIFNOPLUGSAVAILABLE DestinyDestinySocketVisibility = "3"
)