/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// DestinyManifest is the external-facing contract for just the properties needed by those calling the Destiny Platform.
type DestinyConfigDestinyManifest struct {
	Version string `json:"version,omitempty"`
	MobileAssetContentPath string `json:"mobileAssetContentPath,omitempty"`
	MobileGearAssetDataBases []DestinyConfigGearAssetDataBaseDefinition `json:"mobileGearAssetDataBases,omitempty"`
	MobileWorldContentPaths map[string]string `json:"mobileWorldContentPaths,omitempty"`
	MobileClanBannerDatabasePath string `json:"mobileClanBannerDatabasePath,omitempty"`
	MobileGearCDN map[string]string `json:"mobileGearCDN,omitempty"`
}
