/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// For now, this isn't used for much: it's a record of the recent refundable purchases that the user has made. In the future, it could be used for providing refunds/buyback via the API. Wouldn't that be fun?
type DestinyEntitiesProfilesDestinyVendorReceiptsComponent struct {
	// The receipts for refundable purchases made at a vendor.
	Receipts []DestinyVendorsDestinyVendorReceipt `json:"receipts,omitempty"`
}
