/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type DestinyDefinitionsDestinyVendorGroupReference struct {
	// The DestinyVendorGroupDefinition to which this Vendor can belong.
	VendorGroupHash int32 `json:"vendorGroupHash,omitempty"`
}
