/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyDestinyActivityNavPointType int32

// List of Destiny.DestinyActivityNavPointType
const (
	INACTIVE DestinyDestinyActivityNavPointType = "0"
	PRIMARYOBJECTIVE DestinyDestinyActivityNavPointType = "1"
	SECONDARYOBJECTIVE DestinyDestinyActivityNavPointType = "2"
	TRAVELOBJECTIVE DestinyDestinyActivityNavPointType = "3"
	PUBLICEVENTOBJECTIVE DestinyDestinyActivityNavPointType = "4"
	AMMOCACHE DestinyDestinyActivityNavPointType = "5"
	POINTTYPEFLAG DestinyDestinyActivityNavPointType = "6"
	CAPTUREPOINT DestinyDestinyActivityNavPointType = "7"
	DEFENSIVEENCOUNTER DestinyDestinyActivityNavPointType = "8"
	GHOSTINTERACTION DestinyDestinyActivityNavPointType = "9"
	KILLAI DestinyDestinyActivityNavPointType = "10"
	QUESTITEM DestinyDestinyActivityNavPointType = "11"
	PATROLMISSION DestinyDestinyActivityNavPointType = "12"
	INCOMING DestinyDestinyActivityNavPointType = "13"
	ARENAOBJECTIVE DestinyDestinyActivityNavPointType = "14"
	AUTOMATIONHINT DestinyDestinyActivityNavPointType = "15"
	TRACKEDQUEST DestinyDestinyActivityNavPointType = "16"
)