/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyTierType int32

// List of Destiny.TierType
const (
	UNKNOWN DestinyTierType = "0"
	CURRENCY DestinyTierType = "1"
	BASIC DestinyTierType = "2"
	COMMON DestinyTierType = "3"
	RARE DestinyTierType = "4"
	SUPERIOR DestinyTierType = "5"
	EXOTIC DestinyTierType = "6"
)