/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type GroupsV2GroupAction struct {
	// Type of group, either Bungie.net hosted group, or a game services hosted clan.
	GroupType GroupsV2GroupType `json:"groupType,omitempty"`
	Name string `json:"name,omitempty"`
	About string `json:"about,omitempty"`
	Motto string `json:"motto,omitempty"`
	Theme string `json:"theme,omitempty"`
	AvatarImageIndex int32 `json:"avatarImageIndex,omitempty"`
	Tags string `json:"tags,omitempty"`
	IsPublic bool `json:"isPublic,omitempty"`
	MembershipOption GroupsV2MembershipOption `json:"membershipOption,omitempty"`
	IsPublicTopicAdminOnly bool `json:"isPublicTopicAdminOnly,omitempty"`
	IsDefaultPostPublic bool `json:"isDefaultPostPublic,omitempty"`
	AllowChat bool `json:"allowChat,omitempty"`
	IsDefaultPostAlliance bool `json:"isDefaultPostAlliance,omitempty"`
	ChatSecurity GroupsV2ChatSecuritySetting `json:"chatSecurity,omitempty"`
	Callsign string `json:"callsign,omitempty"`
	Locale string `json:"locale,omitempty"`
	Homepage GroupsV2GroupHomepage `json:"homepage,omitempty"`
	// When operation needs a platform specific account ID for the present user, use this property. In particular, groupType of Clan requires this value to be set.
	PlatformMembershipType BungieMembershipType `json:"platformMembershipType,omitempty"`
}
