/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// GroupsV2HostGuidedGamesPermissionLevel : Used for setting the guided game permission level override (admins and founders can always host guided games).
type GroupsV2HostGuidedGamesPermissionLevel int32

// List of GroupsV2.HostGuidedGamesPermissionLevel
const (
	NONE GroupsV2HostGuidedGamesPermissionLevel = "0"
	BEGINNER GroupsV2HostGuidedGamesPermissionLevel = "1"
	MEMBER GroupsV2HostGuidedGamesPermissionLevel = "2"
)