/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type GlobalAlertLevel int32

// List of GlobalAlertLevel
const (
	UNKNOWN GlobalAlertLevel = "0"
	BLUE GlobalAlertLevel = "1"
	YELLOW GlobalAlertLevel = "2"
	RED GlobalAlertLevel = "3"
)