/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyItemType : An enumeration that indicates the high-level \"type\" of the item, attempting to iron out the context specific differences for specific instances of an entity. For instance, though a weapon may be of various weapon \"Types\", in DestinyItemType they are all classified as \"Weapon\". This allows for better filtering on a higher level of abstraction for the concept of types.   This enum is provided for historical compatibility with Destiny 1, but an ideal alternative is to use DestinyItemCategoryDefinitions and the DestinyItemDefinition.itemCategories property instead. Item Categories allow for arbitrary hierarchies of specificity, and for items to belong to multiple categories across multiple hierarchies simultaneously. For this enum, we pick a single type as a \"best guess\" fit.   NOTE: This is not all of the item types available, and some of these are holdovers from Destiny 1 that may or may not still exist.   I keep updating these because they're so damn convenient. I guess I shouldn't fight it.
type DestinyDestinyItemType int32

// List of Destiny.DestinyItemType
const (
	NONE DestinyDestinyItemType = "0"
	CURRENCY DestinyDestinyItemType = "1"
	ARMOR DestinyDestinyItemType = "2"
	WEAPON DestinyDestinyItemType = "3"
	MESSAGE DestinyDestinyItemType = "7"
	ENGRAM DestinyDestinyItemType = "8"
	CONSUMABLE DestinyDestinyItemType = "9"
	EXCHANGEMATERIAL DestinyDestinyItemType = "10"
	MISSIONREWARD DestinyDestinyItemType = "11"
	QUESTSTEP DestinyDestinyItemType = "12"
	QUESTSTEPCOMPLETE DestinyDestinyItemType = "13"
	EMBLEM DestinyDestinyItemType = "14"
	QUEST DestinyDestinyItemType = "15"
	SUBCLASS DestinyDestinyItemType = "16"
	CLANBANNER DestinyDestinyItemType = "17"
	AURA DestinyDestinyItemType = "18"
	MOD DestinyDestinyItemType = "19"
	DUMMY DestinyDestinyItemType = "20"
	SHIP DestinyDestinyItemType = "21"
	VEHICLE DestinyDestinyItemType = "22"
	EMOTE DestinyDestinyItemType = "23"
	GHOST DestinyDestinyItemType = "24"
	PACKAGE DestinyDestinyItemType = "25"
	BOUNTY DestinyDestinyItemType = "26"
)