/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// Represents a category of \"summary\" rewards that can be earned for the Milestone regardless of specific quest rewards that can be earned.
type DestinyMilestonesDestinyMilestoneRewardCategory struct {
	// Look up the relevant DestinyMilestoneDefinition, and then use rewardCategoryHash to look up the category info in DestinyMilestoneDefinition.rewards.
	RewardCategoryHash int32 `json:"rewardCategoryHash,omitempty"`
	// The individual reward entries for this category, and their status.
	Entries []DestinyMilestonesDestinyMilestoneRewardEntry `json:"entries,omitempty"`
}
