/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type ApplicationsOAuthApplicationType int32

// List of Applications.OAuthApplicationType
const (
	NONE ApplicationsOAuthApplicationType = "0"
	CONFIDENTIAL ApplicationsOAuthApplicationType = "1"
	PUBLIC ApplicationsOAuthApplicationType = "2"
)