/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyDefinitionsDestinyTalentNodeStepLightAbilities int32

// List of Destiny.Definitions.DestinyTalentNodeStepLightAbilities
const (
	NONE DestinyDefinitionsDestinyTalentNodeStepLightAbilities = "0"
	GRENADES DestinyDefinitionsDestinyTalentNodeStepLightAbilities = "1"
	MELEE DestinyDefinitionsDestinyTalentNodeStepLightAbilities = "2"
	MOVEMENTMODES DestinyDefinitionsDestinyTalentNodeStepLightAbilities = "4"
	ORBS DestinyDefinitionsDestinyTalentNodeStepLightAbilities = "8"
	SUPERENERGY DestinyDefinitionsDestinyTalentNodeStepLightAbilities = "16"
	SUPERMODS DestinyDefinitionsDestinyTalentNodeStepLightAbilities = "32"
	ALL DestinyDefinitionsDestinyTalentNodeStepLightAbilities = "63"
)