/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type DestinyHistoricalStatsDestinyPostGameCarnageReportEntry struct {
	// Standing of the player
	Standing int32 `json:"standing,omitempty"`
	// Score of the player if available
	Score DestinyHistoricalStatsDestinyHistoricalStatsValue `json:"score,omitempty"`
	// Identity details of the player
	Player DestinyHistoricalStatsDestinyPlayer `json:"player,omitempty"`
	// ID of the player's character used in the activity.
	CharacterId int64 `json:"characterId,omitempty"`
	// Collection of stats for the player in this activity.
	Values map[string]DestinyHistoricalStatsDestinyHistoricalStatsValue `json:"values,omitempty"`
	// Extended data extracted from the activity blob.
	Extended DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData `json:"extended,omitempty"`
}
