/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type GroupsV2GroupHomepage int32

// List of GroupsV2.GroupHomepage
const (
	WALL GroupsV2GroupHomepage = "0"
	FORUM GroupsV2GroupHomepage = "1"
	ALLIANCEFORUM GroupsV2GroupHomepage = "2"
)