/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
import (
	"time"
)

type GlobalAlert struct {
	AlertKey string `json:"AlertKey,omitempty"`
	AlertHtml string `json:"AlertHtml,omitempty"`
	AlertTimestamp time.Time `json:"AlertTimestamp,omitempty"`
	AlertLink string `json:"AlertLink,omitempty"`
	AlertLevel GlobalAlertLevel `json:"AlertLevel,omitempty"`
	AlertType GlobalAlertType `json:"AlertType,omitempty"`
	StreamInfo StreamInfo `json:"StreamInfo,omitempty"`
}
