/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyUnlockValueUiStyle : If you're showing an unlock value in the UI, this is the format in which it should be shown. You'll have to build your own algorithms on the client side to determine how best to render these options.
type DestinyDestinyUnlockValueUiStyle int32

// List of Destiny.DestinyUnlockValueUIStyle
const (
	AUTOMATIC DestinyDestinyUnlockValueUiStyle = "0"
	FRACTION DestinyDestinyUnlockValueUiStyle = "1"
	CHECKBOX DestinyDestinyUnlockValueUiStyle = "2"
	PERCENTAGE DestinyDestinyUnlockValueUiStyle = "3"
	DATETIME DestinyDestinyUnlockValueUiStyle = "4"
	FRACTIONFLOAT DestinyDestinyUnlockValueUiStyle = "5"
	INTEGER DestinyDestinyUnlockValueUiStyle = "6"
	TIMEDURATION DestinyDestinyUnlockValueUiStyle = "7"
	HIDDEN DestinyDestinyUnlockValueUiStyle = "8"
	MULTIPLIER DestinyDestinyUnlockValueUiStyle = "9"
)