/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type DestinyComponentsRecordsDestinyProfileRecordsComponent struct {
	// Your \"Triumphs\" score.
	Score int32 `json:"score,omitempty"`
	// If this profile is tracking a record, this is the hash identifier of the record it is tracking.
	TrackedRecordHash int32 `json:"trackedRecordHash,omitempty"`
	Records map[string]DestinyComponentsRecordsDestinyRecordComponent `json:"records,omitempty"`
}
