/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyPlugAvailabilityMode : This enum determines whether the plug is available to be inserted.  - Normal means that all existing rules for plug insertion apply.  - UnavailableIfSocketContainsMatchingPlugCategory means that the plug is only available if the socket does NOT match the plug category.  - AvailableIfSocketContainsMatchingPlugCategory means that the plug is only available if the socket DOES match the plug category.  For category matching, use the plug's \"plugCategoryIdentifier\" property, comparing it to
type DestinyPlugAvailabilityMode int32

// List of Destiny.PlugAvailabilityMode
const (
	NORMAL DestinyPlugAvailabilityMode = "0"
	UNAVAILABLEIFSOCKETCONTAINSMATCHINGPLUGCATEGORY DestinyPlugAvailabilityMode = "1"
	AVAILABLEIFSOCKETCONTAINSMATCHINGPLUGCATEGORY DestinyPlugAvailabilityMode = "2"
)