/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type GroupsV2GroupMemberCountFilter int32

// List of GroupsV2.GroupMemberCountFilter
const (
	ALL GroupsV2GroupMemberCountFilter = "0"
	ONETOTEN GroupsV2GroupMemberCountFilter = "1"
	ELEVENTOONEHUNDRED GroupsV2GroupMemberCountFilter = "2"
	GREATERTHANONEHUNDRED GroupsV2GroupMemberCountFilter = "3"
)