/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyRecordState : A Flags enumeration where each bit represents a possible state that a Record/Triumph can be in.
type DestinyDestinyRecordState int32

// List of Destiny.DestinyRecordState
const (
	NONE DestinyDestinyRecordState = "0"
	RECORDREDEEMED DestinyDestinyRecordState = "1"
	REWARDUNAVAILABLE DestinyDestinyRecordState = "2"
	OBJECTIVENOTCOMPLETED DestinyDestinyRecordState = "4"
	OBSCURED DestinyDestinyRecordState = "8"
	INVISIBLE DestinyDestinyRecordState = "16"
	ENTITLEMENTUNOWNED DestinyDestinyRecordState = "32"
	CANEQUIPTITLE DestinyDestinyRecordState = "64"
)