/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyActivityModeCategory : Activity Modes are grouped into a few possible broad categories.
type DestinyDestinyActivityModeCategory int32

// List of Destiny.DestinyActivityModeCategory
const (
	NONE DestinyDestinyActivityModeCategory = "0"
	PVE DestinyDestinyActivityModeCategory = "1"
	PVP DestinyDestinyActivityModeCategory = "2"
	PVECOMPETITIVE DestinyDestinyActivityModeCategory = "3"
)