/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type DestinyAdvancedAwaPermissionRequested struct {
	// Type of advanced write action.
	Type DestinyAdvancedAwaType `json:"type,omitempty"`
	// Item instance ID the action shall be applied to. This is optional for all but a new AwaType values. Rule of thumb is to provide the item instance ID if one is available.
	AffectedItemId int64 `json:"affectedItemId,omitempty"`
	// Destiny membership type of the account to modify.
	MembershipType BungieMembershipType `json:"membershipType,omitempty"`
	// Destiny character ID, if applicable, that will be affected by the action.
	CharacterId int64 `json:"characterId,omitempty"`
}
