/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyDefinitionsDestinyTalentNodeStepDamageTypes int32

// List of Destiny.Definitions.DestinyTalentNodeStepDamageTypes
const (
	NONE DestinyDefinitionsDestinyTalentNodeStepDamageTypes = "0"
	KINETIC DestinyDefinitionsDestinyTalentNodeStepDamageTypes = "1"
	ARC DestinyDefinitionsDestinyTalentNodeStepDamageTypes = "2"
	SOLAR DestinyDefinitionsDestinyTalentNodeStepDamageTypes = "4"
	VOID DestinyDefinitionsDestinyTalentNodeStepDamageTypes = "8"
	ALL DestinyDefinitionsDestinyTalentNodeStepDamageTypes = "15"
)