/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

// The collection of all items currently being sold by a specific Vendor and visible to the given character for which the request was made.
type DestinyComponentsVendorsDestinyVendorSaleItemSetComponent struct {
	// The items being sold by this vendor, keyed by the vendorItemIndex of the item being sold. (because showing sale items depends on the ordering dictated by the categories being shown - see DestinyVendorCategoryComponent - this is a dictionary for quick lookup capability.)
	SaleItems map[string]DestinyEntitiesVendorsDestinyVendorSaleItemComponent `json:"saleItems,omitempty"`
}
