/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
// DestinyDestinyProgressionScope : There are many Progressions in Destiny (think Character Level, or Reputation). These are the various \"Scopes\" of Progressions, which affect many things: * Where/if they are stored * How they are calculated * Where they can be used in other game logic
type DestinyDestinyProgressionScope int32

// List of Destiny.DestinyProgressionScope
const (
	ACCOUNT DestinyDestinyProgressionScope = "0"
	CHARACTER DestinyDestinyProgressionScope = "1"
	CLAN DestinyDestinyProgressionScope = "2"
	ITEM DestinyDestinyProgressionScope = "3"
	IMPLICITFROMEQUIPMENT DestinyDestinyProgressionScope = "4"
	MAPPED DestinyDestinyProgressionScope = "5"
	MAPPEDAGGREGATE DestinyDestinyProgressionScope = "6"
	MAPPEDSTAT DestinyDestinyProgressionScope = "7"
	MAPPEDUNLOCKVALUE DestinyDestinyProgressionScope = "8"
)