/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type DestinyVendorItemStatus int32

// List of Destiny.VendorItemStatus
const (
	SUCCESS DestinyVendorItemStatus = "0"
	NOINVENTORYSPACE DestinyVendorItemStatus = "1"
	NOFUNDS DestinyVendorItemStatus = "2"
	NOPROGRESSION DestinyVendorItemStatus = "4"
	NOUNLOCK DestinyVendorItemStatus = "8"
	NOQUANTITY DestinyVendorItemStatus = "16"
	OUTSIDEPURCHASEWINDOW DestinyVendorItemStatus = "32"
	NOTAVAILABLE DestinyVendorItemStatus = "64"
	UNIQUENESSVIOLATION DestinyVendorItemStatus = "128"
	UNKNOWNERROR DestinyVendorItemStatus = "256"
	ALREADYSELLING DestinyVendorItemStatus = "512"
	UNSELLABLE DestinyVendorItemStatus = "1024"
	SELLINGINHIBITED DestinyVendorItemStatus = "2048"
	ALREADYOWNED DestinyVendorItemStatus = "4096"
	DISPLAYONLY DestinyVendorItemStatus = "8192"
)