/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie

type DestinyHistoricalStatsDestinyClanAggregateStat struct {
	// The id of the mode of stats (allPvp, allPvE, etc)
	Mode DestinyHistoricalStatsDefinitionsDestinyActivityModeType `json:"mode,omitempty"`
	// The id of the stat
	StatId string `json:"statId,omitempty"`
	// Value of the stat for this player
	Value DestinyHistoricalStatsDestinyHistoricalStatsValue `json:"value,omitempty"`
}
