/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type GroupsV2GroupAllianceStatus int32

// List of GroupsV2.GroupAllianceStatus
const (
	UNALLIED GroupsV2GroupAllianceStatus = "0"
	PARENT GroupsV2GroupAllianceStatus = "1"
	CHILD GroupsV2GroupAllianceStatus = "2"
)