/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * API version: 2.3.2
 * Contact: support@bungie.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package bungie
type GroupsV2Capabilities int32

// List of GroupsV2.Capabilities
const (
	NONE GroupsV2Capabilities = "0"
	LEADERBOARDS GroupsV2Capabilities = "1"
	CALLSIGN GroupsV2Capabilities = "2"
	OPTIONALCONVERSATIONS GroupsV2Capabilities = "4"
	CLANBANNER GroupsV2Capabilities = "8"
	D2INVESTMENTDATA GroupsV2Capabilities = "16"
	TAGS GroupsV2Capabilities = "32"
	ALLIANCES GroupsV2Capabilities = "64"
)